### ISSUE TITLE
Plan out presentation

### ISSUE THREAD

**Issue by Kaystaken** [Kaystaken/food4foodies#14]
![Image](https://github.com/Kaystaken/aire-exec/assets/148396597/f437892c-bd8f-4908-9246-b3d33d7feca9)

**Comment by TammyH7** [comment]
Note = Must be interactive (i.e: accept and respond to user input)

**Comment by TammyH7** [comment]
Note = Must NOT use alerts, confirms, or prompts (look into modals)
